绝妙的想法，我简直就是一个天才
VScode？ AIcode!
以文本页面为展示空间的浏览器，这才是AI Agent的正确应用。
点击跳转或者单纯的空白文本太无聊了,AI的联想和VScode里的对之前的语句的记忆非常好用。
如果我想要打开一个网页，我在这里用~打开百度
~打开bilibili
~打开github
就想命令行操控那样，只不过是用自然语言。

##功能
那么这样一个操作系统还有什么功能呢？
比如跳转窗口的时候用终端的方式预览。
比如加载窗口的时候不是全屏等待加载，而是小窗启动，同时主界面还可以和AI互动！
比如你想要打开一个长时间使用的软件，AI会帮你记住你用这个软件用了多久，进入某软件的时候还是沉浸式的体验。比如，播放视频和查看评论？
按home件唤出桌面AI并暂停其他活动。

##任务处理
主动上传文件，多次对话分析，这是现在的AI帮助我们实际处理任务的方式。
但，我们还有另外一种选择。即，把所有的文件都让AI记住，比如可以默认全部下载下文件，然后AI逐个阅读，在内存（或其他运行资源）还足够时，不进行提醒，等到资源不足时，通过对话及二次确认的方式删除一些文件。
这样的话，我们就可以畅想一个新的工作方式。
即，AI主动帮助你梳理可能的任务，并记下DDL，省去最初的规划环节。

##使用它
如何在完成工作任务和进行娱乐通信等事务进行平衡？
通常的方法是利用人为主观利用时间管理技巧来安排这些事物。
但我们可以，让AI本身成为时间管理大师，你的习惯怎么样？你是否真的完成了这样的工作？你按照那样工作的话会得到正反馈吗？
本质上，让AI成为你的伴侣，它了解你在工作、电子游戏、利用电子设备社交甚至和朋友聊天等等的东西。

##如何才能做到让它了解这么多又不会让用户麻烦？
1. 常态的“看”，特殊的“说”。这是一个I人朋友，它的沟通不会那么的奔放，隐藏在水面下的收集和数据处理是后续要去做细化的东西。


怎么说呢，我感觉我的工作是不是需要模式化一下。

比如说，我需要一个定时器，开始的时候先听一首歌?